### ISSUE TITLE
Caption data

### ISSUE THREAD

**Issue by lhallee** [generatebio/chroma#1]
Hello,

Amazing work! Curious if the captions used to train the ProCap will be made available.
Best,
Logan

**Comment by aismail3-gnr8** [comment]
Thanks! The captions used to train ProCap are taken from the descriptive text for PDB structures, as well as UniProt functional comments for individual chains. For more details, see Section T.2 of the [Supplemental Information of our paper](https://www.nature.com/articles/s41586-023-06728-8#Sec10).
