### ISSUE TITLE
Running chroma from docker

### ISSUE THREAD

**Issue by e-osipov** [generatebio/chroma#11]
Hi everyone,

I wonder how to properly create docker image and run container in order to utilize GPU? For now, chroma is running using CPU only.

What I did:
- I created an image from `Dockerfile` using `docker build -t chroma .` command
- Container was started using `docker run -i -t --runtime=nvidia --gpus all chroma`
- `nvidia-smi` within container will show that I have GPU available
However, any example will run on CPU, using all available cores.

**Comment by wujiewang** [comment]
Ok, I think torch is somehow not installed properly with cuda support, this is weird....

![image](https://github.com/generatebio/chroma/assets/150089758/f23b4261-1422-4d4b-8e46-fdde3c81b0a3)

I will update the Dockerfile to explicitly specify torch version with cuda=11.3.

Sorry about that!

**Comment by wujiewang** [comment]
Oh, I guess cuda=11.3.1 is too old for torch=2.1.1, will just do 

`pip install torch==1.12.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113`

**Comment by wujiewang** [comment]
ok, resolved with d5f5787!! thanks for reporting this issue!
