### ISSUE TITLE
Protein folding

### ISSUE THREAD

**Issue by kushnarang** [generatebio/chroma#12]
Thank you for making this excellent project open source!

Is Chroma able to do protein folding, as in, provided an amino acid sequence with no structural information (i.e. a FASTA file) generate a 3D structure for that sequence?

I don't see any examples of this in the notebooks or demo files.

**Comment by wujiewang** [comment]
Thanks for the question! Chroma is built for generative protein design to sample P(structure, seq), not for structure prediction P(structure | seq). ESMfold, Omegafold, and Alphafold are properly more relevant tools, and we reported Refolding successes on Chroma proteins in our Supplementary materials.

However, you can check out SequenceConditioner for masked or unmaksed sequence conditioning: https://github.com/generatebio/chroma/blob/d5f57876ea0f73b3a6c62cf9437f258a71e81b67/chroma/layers/structure/conditioners.py#L170
