### ISSUE TITLE
Installation fails on windows 11 and wsl2 with python >= 3.11

### ISSUE THREAD

**Issue by eugenio** [generatebio/chroma#17]
See attached file for error trace

I tried with python 3.11.6 and 3.12.0, both are no go.
I tried from git repo with same result.
I tried using a venv in python 3.11.6, but no go either.

the problem is scikit-learn version that is still using distutils or setuptools which are deprecated.

Even using a compatible version of setuptools the installation is not going ahead of this point above.

On WSL2 there's the same problem.

could you please advice?

[error trace chroma.txt](https://github.com/generatebio/chroma/files/13459802/error.trace.chroma.txt)

**Comment by wujiewang** [comment]
Hey, can you try a older python version like 3.9? 

 We also provided a Dockerfile in case you run into environment setup issue.

**Comment by eugenio** [comment]
With python 3.9 the installation complete successfully.

Thank you!

**Comment by wujiewang** [comment]
Great to hear. We will work on support for python>=3.10
