### ISSUE TITLE
Conditioning on AA composition

### ISSUE THREAD

**Issue by AlexWindels** [generatebio/chroma#20]
Hi,

Amazing work you all did developing Chroma. Whilst playing around, I was wondering if there's a way to condition the sequence/structure on residue content. So for example if it is possible to bias the composition towards alanine and serine, representing x% and y% of all residues respectively? 

Best,

Alex

**Comment by wujiewang** [comment]
Hey, that is an interesting idea! You could try this by modifying the [SequenceConditioner](https://github.com/generatebio/chroma/blob/ca86eaae1ffcfc4ec128f4ef61be044228f36e8a/chroma/layers/structure/conditioners.py#L170) and compute a differential restraint energy that penalize deviation from target composition, not sure how well that will work though, but an interesting project idea for our Condition ecosystem!

**Comment by wujiewang** [comment]
Closing this for now, but feel free to reopen if you have more to discuss.
