### ISSUE TITLE
Binder design notebook with specified hotspot

### ISSUE THREAD

**Issue by Samuel-gwb** [generatebio/chroma#27]
Great work and elegant methods!

Will anyone share a notebook for binder design that can specify hotspot residues on the receptor?

Many thanks!

**Comment by wujiewang** [comment]
Hi, thanks for the question. Hope https://github.com/generatebio/chroma/issues/37 and https://github.com/generatebio/chroma/issues/36 will give you some ideas on how to do this. Let us know if you need more help on this.

**Comment by Samuel-gwb** [comment]
Great, thanks for all of mentioned discussions !

**Comment by kushnarang** [comment]
Hi @wujiewang , I wanted to follow up on the conversation about hotspots. Unless I'm missing something, all the examples I have seen show how to do hotspots when re-designing/re-sampling an existing chain. 

Are there any examples of doing **de-novo** binder design with a hotspot similar to RFDiffusion is able to?
