### ISSUE TITLE
'display' issue

### ISSUE THREAD

**Issue by venuv** [generatebio/chroma#29]
Hi, i'm running on a MacMini via remote login and get an error on the demo (simple 200-amino acid monomeric protein) example .. any thoughts appreciated

----
python sample_protein.py
Data saved to /var/folders/7w/86cljl2560722vp9qy4rff4r0000gn/T/chroma_weights/90e339502ae6b372797414167ce5a632/weights.pt
Computing reference stats for 2g3n
Data saved to /var/folders/7w/86cljl2560722vp9qy4rff4r0000gn/T/chroma_weights/03a3a9af343ae74998768a2711c8b7ce/weights.pt
Loaded from cache
Integrating SDE: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [09:40<00:00,  1.16s/it]
Potts Sampling: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [00:04<00:00, 112.53it/s]
Sequential decoding: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:01<00:00, 193.11it/s]
Traceback (most recent call last):
  File "/Users/venuv62/Desktop/biology/sample_protein.py", line 9, in <module>
    display(protein)
NameError: name 'display' is not defined

**Comment by aismail3-gnr8** [comment]
Are you running from a terminal? The `display` function won't work in this case, but you can still print out a text representation of the result with `print(protein)`, or save it with `protein.to_CIF(filename)`.

**Comment by venuv** [comment]
@aismail3-gnr8 makes sense. Ended up using NGLView within a notebook
