### ISSUE TITLE
Question for CDRs Method

### ISSUE THREAD

**Issue by Charlesjc-lab** [generatebio/chroma#33]
When I attempted to redesign the complementarity-determining regions (CDRs) of the antibody, I found that it is only possible to fix multiple epitopes using a method similar to the one depicted in the diagram below. Has anyone tried this approach? Are there any other methods available?
![屏幕截图 2023-12-26 152024](https://github.com/generatebio/chroma/assets/154870985/3ba22641-0c50-4645-8c7f-35b43298f704)

**Comment by wujiewang** [comment]
Thanks for submitting the issue!

 you can also provide a binary design mask, I think that will give you more customizability.  Also see https://github.com/generatebio/chroma/issues/5

**Comment by Charlesjc-lab** [comment]
Thanks for the answer! 

Design_mask is a smarter approach compared to the method I'm currently using. #5

**Comment by wujiewang** [comment]
nice! thanks for the feedback. I am closing this for now, but feel free to reopen or open new issues.
