### ISSUE TITLE
problem about "protein = chroma.design(protein)"

### ISSUE THREAD

**Issue by ning-2022** [generatebio/chroma#34]
Hi Chroma experts,

   Thanks for your distinguished program for protein design. I'm trying to use it on my laptop that having one GPU and one CPU.  When I tried to use this command from tutorial in the python3 interface, like that " protein = chroma.design(protein) " , some errors were accidentally appeared. 

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

Please help me, I also am a freshman in Python programming. 

Best regards,
Ning

**Comment by ning-2022** [comment]
Hi, I have a quick feedback that if I modifies the input path like this " protein = Protein('/home/neil/sample.cif', device='cuda:0') ", this kind of problem seems to be solved.   But I'm not sure this way is correct.  Any suggestions are welcome.

Ning

**Comment by wujiewang** [comment]
That sounds like the right fix, Protein and Chroma need to be on the same device, in this case "cuda".

**Comment by ning-2022** [comment]
> That sounds like the right fix, Protein and Chroma need to be on the same device, in this case "cuda".

Thanks for your reply.  This program is really amazing.
