### ISSUE TITLE
Prediction of secondary structure

### ISSUE THREAD

**Issue by ahof1704** [generatebio/chroma#38]
Hi,

In figures 5g and 5h of your paper, you indicate that Chroma can predict the alpha and beta content of the generated molecules. Could you indicate the code you use for this prediction? 

Thanks 
Antonio

**Comment by wujiewang** [comment]
Thanks for the question, you can just use the log likelihood from `ProClassConditioner` for the content probability. It is a trained model for conditioning.

But you just use any DSSP programs (e.g. https://github.com/ShintaroMinami/PyDSSP ) to compute secondary structure contents, which will be more accurate.

**Comment by wujiewang** [comment]
closing this issue for now. feel free to reopen or submit a new issue if you have follow-up questions.
