### ISSUE TITLE
Trajectory cif file won't open in ChimeraX

### ISSUE THREAD

**Issue by Guillawme** [generatebio/chroma#4]
Hello,

This is so cool! I just tried playing with the demo colab notebook and ran the "get a protein" example with the default 160 residues, and downloaded the trajectory cif file. I can open it in PyMOL and play the trajectory. But when trying to open it in ChimeraX (a viewer I am more familiar with), I get this error:

```
Summary of feedback from opening /home/guillaume/Downloads/protein_trajectory.cif
warnings	Skipping atom_site category: Missing column 'type_symbol' near line 231
No mmCIF models found.
```

Attaching this particular [protein_trajectory.cif.txt](https://github.com/generatebio/chroma/files/13375459/protein_trajectory.cif.txt) file just in case it is helpful, but I suspect this would happen with any file, just with the error at a different line (I had to add a .txt extension for GitHub to accept uploading, you will need to rename it and remove this extension).

**Comment by Guillawme** [comment]
I get the exact same error when trying to open the corresponding [protein.cif.txt](https://github.com/generatebio/chroma/files/13375515/protein.cif.txt) file with ChimeraX. Also opens fine in PyMOL.

**Comment by agarrubio** [comment]
I have the same problem. I had to convert that 'cif' to 'pdb':
```https://mmcif.pdbj.org/converter/index.php?l=en```

There is also this software, which I haven't tried:
```https://github.com/PDB-REDO/cif-tools```

**Comment by wujiewang** [comment]
We don't use ChimeraX, so we are not aware of the problem. We will try to look into it.

For the generated `Protein` Object, you can also dump to pdb directly with `.to_PDB()` if that is easier.

**Comment by wujiewang** [comment]
@Guillawme @agarrubio 

hey, @ggrigoryanv fixed the write_CIF functions by adding atom elemnt types with 2f3f32a0814821fdcff723088b699b94c1b374b0. I tested it and it works. You can get the change by installing from github.

Thanks so much for the feedback.
