### ISSUE TITLE
ImportError: cannot import name 'api' from 'chroma'

### ISSUE THREAD

**Issue by nickyoungforu** [generatebio/chroma#6]
running:
from chroma import api
api.register_key("xxx")

ImportError: cannot import name 'api' from 'chroma' (/opt/conda/envs/python37/lib/python3.7/site-packages/chroma/__init__.py)

**Comment by wujiewang** [comment]
I just tested the installation, it should be working. 

Can you check `/opt/conda/envs/python37/lib/python3.7/site-packages/chroma/` to see if you installed chroma properly?

**Comment by wujiewang** [comment]
closed this due to inactivity, but feel free to reopen with more system details.
